title: Default File

create:
  width: 2000

fields:

  alt:
    label: Alternativer Text
    type: text
    width: 1/3

  copyright:
    label: Copyright
    type: text
    width: 1/3

  link:
    label: Link
    type: url
    width: 1/3