version: '3.1'
services:
  php:
    image: webdevops/php-apache-dev:8.1-alpine
    restart: unless-stopped
    working_dir: /
    # ports:
    #   - "8081:80" # for debugging without nginx-proxy
    volumes:
      - ./:/app:rw,cached
    environment:
      WEB_DOCUMENT_ROOT: /app/website
      PHP_DISPLAY_ERRORS: 1
      PHP_MEMORY_LIMIT: 2048M
      PHP_MAX_EXECUTION_TIME: -1
      VIRTUAL_HOST: boilerplate.local
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      
      # XDEBUG
      XDEBUG_MODE: develop,debug
      XDEBUG_START_WITH_REQUEST: yes
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_REMOTE_AUTOSTART: 1
      
networks:
  default:
    name: nginx-proxy
    external: true
