<?php return [
	'debug'                         => false,
	'panel'                         => false,
	'languages'                     => true,
	'date'                          => [
		'handler' => 'strftime'
	],
	'sylvainjule.matomo.url'        => 'https://stats.kleiner-als.de', #required
	'sylvainjule.matomo.id'         => false, #required
	'sylvainjule.matomo.token'      => '', // #required for the panel integration
	'sylvainjule.matomo.active'     => false,
	'sylvainjule.matomo.debug'      => false,
	'sylvainjule.matomo.trackUsers' => false,
	'sylvainjule.matomo.blacklist'  => ['127.0.0.1', '::1'],

	'schnti.autoresize.max' => 2000,

	//	'schnti.sitemap.excludeSites'        => ['error', 'sitemap', 'thankyou'],
	//	'schnti.sitemap.excludeTemplates'    => [],
	//	'schnti.sitemap.includeSites'        => ['impressum', 'datenschutzerklaerung'],
	//	'schnti.sitemap.showUnlistedSites'   => false,
	//	'schnti.sitemap.importantSites'      => [],
	//  'schnti.sitemap.showOnePagerModules' => false,

	'schnti.legal.username' => '',
	'schnti.legal.password' => '',
	'schnti.legal.cache.data' => false,
	'schnti.legal.data'     => [
		"datenschutz/datenschutz-auf-einen-blick/allgemeine-hinweise",
		"datenschutz/datenschutz-auf-einen-blick/datenerfassung-auf-unserer-website",
		//							"datenschutz/datenschutz-auf-einen-blick/analyse-tools-und-tools-von-drittanbietern",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/datenschutz",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/hinweis-zur-verantwortlichen-stelle",
		//							"datenschutz/allgemeine-hinweise-und-pflichtinformationen/gesetzlich-vorgeschriebener-datenschutzbeauftragter",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/widerruf-ihrer-einwilligung-zur-datenverarbeitung",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/widerspruchsrecht-gegen-die-datenerhebung-in-besonderen-fallen-sowie-gegen-direktwerbung-art-21-dsgvo",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/beschwerderecht-bei-der-zustaendigen-aufsichtsbehoerde",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/recht-auf-datenubertragbarkeit",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/ssl-bzw-tls-verschlusselung",
		//							"datenschutz/allgemeine-hinweise-und-pflichtinformationen/verschlusselter-zahlungsverkehr-auf-dieser-website",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/auskunft-sperrung-loschung",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/recht-auf-einschrankung-der-verarbeitung",
		"datenschutz/allgemeine-hinweise-und-pflichtinformationen/widerspruch-gegen-werbe-mails",
		"datenschutz/datenerfassung-auf-unserer-website/cookies",
		"datenschutz/datenerfassung-auf-unserer-website/server-log-dateien",
		//							"datenschutz/datenerfassung-auf-unserer-website/kontaktformular",
		"datenschutz/datenerfassung-auf-unserer-website/anfrage-per-e-mail-telefon-oder-telefax",
		//							"datenschutz/datenerfassung-auf-unserer-website/registrierung-auf-dieser-website",
		//							"datenschutz/datenerfassung-auf-unserer-website/registrierung-mit-facebook-connect",
		//							"datenschutz/datenerfassung-auf-unserer-website/verarbeiten-von-daten-kunden-und-vertragsdaten",
		//							"datenschutz/datenerfassung-auf-unserer-website/datenubermittlung-bei-vertragsschluss-fur-online-shops-handler-und-warenversand",
		//							"datenschutz/datenerfassung-auf-unserer-website/datenubermittlung-bei-vertragsschluss-fur-dienstleistungen-und-digitale-inhalte",
		//							"datenschutz/soziale-medien/erecht24-safe-sharing-tool",
		//							"datenschutz/soziale-medien/social-media-plugins-mit-shariff",
		//							"datenschutz/soziale-medien/facebook-plugins-like-and-share-button",
		//							"datenschutz/soziale-medien/twitter-plugin",
		//							"datenschutz/soziale-medien/google-plugin",
		//							"datenschutz/soziale-medien/instagram-plugin",
		//							"datenschutz/soziale-medien/tumblr-plugin",
		//							"datenschutz/soziale-medien/linkedin-plugin",
		//							"datenschutz/soziale-medien/xing-plugin",
		//							"datenschutz/soziale-medien/pinterest-plugin",
		//							"datenschutz/analyse-tools-und-werbung/matomo",
		//							"datenschutz/newsletter/newsletterdaten",
		//							"datenschutz/plugins-und-tools/youtube",
		//							"datenschutz/plugins-und-tools/youtube-mit-erweitertem-datenschutz",
		//							"datenschutz/plugins-und-tools/vimeo",
		//							"datenschutz/plugins-und-tools/google-web-fonts",
		"datenschutz/plugins-und-tools/google-web-fonts-lokal",
		//							"datenschutz/plugins-und-tools/adobe-typekit-web-fonts",
		//							"datenschutz/plugins-und-tools/google-maps",
		//							"datenschutz/plugins-und-tools/google-maps-mit-einwilligung",
		//							"datenschutz/plugins-und-tools/openstreetmap",
		//							"datenschutz/plugins-und-tools/google-recaptcha",
		//							"datenschutz/plugins-und-tools/soundcloud",
		//							"datenschutz/plugins-und-tools/spotify",
		//							"datenschutz/plugins-und-tools/zendesk",
		//							"datenschutz/zahlungsanbieter/paypal",
		//							"datenschutz/zahlungsanbieter/klarna",
		//							"datenschutz/zahlungsanbieter/sofortuberweisung",
		//							"datenschutz/zahlungsanbieter/paydirect",
		//							"datenschutz/eigene-dienste/bewerbungen",
		"disclaimer/haftung-fur-inhalte",
		"disclaimer/haftung-fur-links",
		"disclaimer/urheberrecht"
	],
];