title: Site


tabs:

  content:
    label: Content
    icon: text

    columns:
      - width: 2/3
        sections:

          - headline: Veröffentlicht
            type: pages
            status: listed
            info: " {{ page.moduleDisplayName}}"

          - headline: Ungelistet
            type: pages
            status: unlisted
            info: " {{ page.moduleDisplayName}}"

          - headline: Entwürfe
            type: pages
            status: draft
            info: " {{ page.moduleDisplayName}}"

  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3

        fields:

          seoDescription:
            extends: fields/seo-description
            help: Startseiten SEO Beschreibung und Standard, wenn auf den Unterseiten keine SEO Beschreibung hinterlegt ist (maximal 255 Zeichen).
            placeholder: ""

  disclaimer:
    label: Disclaimer
    icon: settings
    columns:
      - width: 2/3

        fields:

          copyright:
            extends: fields/text
            label: Copyright

          footerLinks:
            extends: fields/text
            label: Links