title: Site


tabs:

  content:
    label: Content
    icon: text

    columns:
      - width: 2/3
        sections:

          # OnePager
          - headline: Module
            type: modules
            parent: site.find('home').find("modules")

          - headline: Seiten
            type: pages

          # Default Page
          #          - headline: Veröffentlicht
          #            type: pages
          #            status: listed
          #
          #          - headline: Ungelistet
          #            type: pages
          #            status: unlisted
          #
          #          - headline: Entwürfe
          #            type: pages
          #            status: draft

  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3

        fields:

          seoDescription:
            extends: fields/seo-description
            help: Startseiten SEO Beschreibung und Standard, wenn auf den Unterseiten keine SEO Beschreibung hinterlegt ist (maximal 255 Zeichen).
            placeholder: ""

  disclaimer:
    label: Disclaimer
    icon: settings
    columns:
      - width: 2/3

        fields:

          copyright:
            extends: fields/text
            label: Copyright

          footerLinks:
            extends: fields/text
            label: Links